# Generated by Django 2.2.3 on 2020-06-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
    ]
