# Generated by Django 3.0.7 on 2020-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(default='/'),
        ),
    ]
