# Generated by Django 3.0.7 on 2020-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200613_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
